### ISSUE TITLE
Cover intermediate image

### ISSUE THREAD

**Issue by luwensu** [jramseye/docker-migrate#5]
`#docker images` will hide the intermediate image by default (-a option is false), so use `#docker images -a` would be better.
For how to generate intermediate image:
`#docker pull fedora`
`#docker run fedora` --> assume the generated container named $TMP
`#docker commit $TMP fedora`
`#docker images` will only show the new fedora, but
`#docker images -a` will show the hidden `<none>:<none>` which is the original "fedora" image

**Comment by jramseye** [comment]
Good catch.  Originally, I had used docker images -a, but switched  back to docker images.  I was trying to delete the images as well, and docker seems to handle deleting intermediate images when it deletes later images, so manually deleting intermediate images as well was giving me problems (things had already been deleted when I was trying to delete them).  But we stopped deleting them, so I will switch it back.

**Comment by jramseye** [comment]
Pushed a fix
